# Generated by Django 3.2.4 on 2021-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('scholarships', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('otheract', models.CharField(max_length=100)),
            ],
        ),
    ]
